### ISSUE TITLE
Enigmail incompatibility

### ISSUE THREAD

**Issue by Natanji** [jikamens/send-later#1]
Enigmail by default encrypts drafts with the sender's key such that the mail provider cannot access the potentially confidential information in a newly drafted mail (even for mails that are later send unencrypted).
When Send Later is used in conjunction, the mail will be saved to drafts in exactly this encrypted form, and then sent to the recipients without first decrypting it or encrypting it for the intended recipients. This means that recipients will receive an unreadable GPG-encrypted message, always.

In order for Send Later and Enigmail to work together, Send Later needs to tell Enigmail that the message is supposed to be brought into its final form (unencrypted, or encrypted with the intended recipient's keys) and THEN saved to drafts, then send it later as intended.

The discussion of this issue (with a workaround, which essentially disables Enigmail) can be found here: https://groups.google.com/forum/#!topic/send-later-users/fPnAVz7PDqw

**Comment by ddddavidee** [comment]
It seems also that Send Later reformat emails after Enigmail signed it, breaking the verification function at recipient side.

**Comment by ianhinder** [comment]
This is an absolutely critical vulnerability.  Since the Google Groups discussion above in 2013, the behaviour has changed.  It no longer sends unreadable messages by default. Instead, it sends unencrypted messages! Emails are being sent out unencrypted, even though when they are composed, they are shown as encrypted.  There is no indication that the email will be sent unencrypted, and the only way to know this is if the recipient notices and tells you.   I suspect that 170f2de is responsible.  There is also a comment about Enigmail in f03aa7b.

This is such a serious problem that I think Send Later should refuse to work if the message is initially encrypted.  It is much better to have the mail sent encrypted immediately than to have it sent unencrypted later.

**Comment by jikamens** [comment]
Unfortunately, it has proven extremely difficult -- it might even be impossible, given the Thunderbird add-on integration framework and how Send Later and Enigmail function -- to make the scheduling of messages with Send Later work safely and reliably when Enigmail is enabled.

Therefore, the only solution I have for this problem is to prevent Send Later from scheduling messages when Enigmail is active.

This has been implemented in https://github.com/jikamens/send-later/commit/ef6305bec436051695baed16d1ba05ce38655504 and released in https://addons.mozilla.org/en-US/seamonkey/addon/send-later-3/versions/?page=1#version-4.4.5beta1. Within a week or two if I don't get any problem reports from beta tester I'll promote it to release 4.4.5 and close this issue.

**Comment by jikamens** [comment]
I released version 4.4.5 today, but it hasn't been reviewed yet and therefore isn't yet updating automatically.

**Comment by jikamens** [comment]
https://addons.mozilla.org/en-US/seamonkey/addon/send-later-3/versions/?page=1#version-4.4.5

**Comment by jikamens** [comment]
Version 4.4.5 of the add-on has been approved by Mozilla.

**Comment by ArsenShnurkov** [comment]
> it has proven extremely difficult -- it might even be impossible, given the Thunderbird add-on integration framework and how Send Later and Enigmail function -- to make the scheduling of messages with Send Later work safely and reliably when Enigmail is enabled.

Where one can read the proof ?

**Comment by jikamens** [comment]
> Where one can read the proof ?

Excuse me?

**Comment by ArsenShnurkov** [comment]
I want more details of what leads to the conclusion that it is too difficult to implement this integration (Send Later with Enigmail in Thunderbird). Ideally, it should be an estimation of implementation difficulty.

**Comment by jikamens** [comment]
Thunderbird does not give add-ons the ability to control the order in which event listeners are called.

Both Send Later and Enigmail use an event listener to do their work when the user goes to send a message.

It is theoretically possible to maybe get Send Later to work properly with Enigmail if its event listener is always called after Enigmail's, but as noted above, it's impossible for me to ensure that's what happens.

The three paths to fixing this are (a) add the ability in the Thunderbird core for add-ons to control the order in which their event listeners are called; (b) make changes directly to Send Later and Enigmail to make them play nicely with each other (this requires cooperation from the Enigmail maintainers); or (c) completely rearchitect how Send Later works.

There's also, I suppose, option (d) build Send Later into Thunderbird so that it no longer needs to be a separate add-on.

(d) isn't going to happen because I don't have the time, I don't think anyone else is interested in doing it, and even if someone were interested in doing it, I'm not sure the people in charge of Thunderbird nowadays would want it.

(c) isn't going to happen because I don't have the time to completely rewrite the add-on and I'm not even sure whether it's possible to rearchitect in a way that is compatible with the Thunderbird add-on framework and addresses this problem.

(a) is unlikely to happen because the maintainers of the relevant code -- which is shared with Firefox -- because I don't have the time to do the work, I don't know of anyone else who is willing to do it, and I'm not even sure the folks who own that code would accept such changes (in fact, I doubt they would).

So that leaves (b). as I [noted recently on the send-later-users mailing list](https://groups.google.com/forum/#!topic/send-later-users/LrHXGRSINjY), I am currently working with one of the Enigmail developers to make that happen, though I don't yet have a timeline.

Incidentally, your first comment above was rude and your second one slightly less so. This is free software and I don't owe you anything, so if you want me to take the time to respond to your inquiries, you'd be well-advised to try making them a bit more polite. Don't expect me to continue to respond if you continue to be rude.

**Comment by ArsenShnurkov** [comment]
That's not rudeness, it's bad knowledge of English language. I will read something about this.

I see way "a" as most reasonable. And you didn't create feature requests to Thunderbird/Enigmail bugtrackers (because you didn't give links to them, and this is why you don't know the opinion of their maintainers).

I don't believe that cooperation with enigmail addon is a good solution. And I agree that integration into thunderbird is not the proper way to resolve this problem.

I didn't understood the "c" way. If it is possible to rearchitect the addon without changing Thunderbird, then it's your bug, not thunderbird's one. So there should be more details given. Using the word "should" i don't require anything from your and your time, may be it's "it would be nice to do in the ideal world"

**Comment by Natanji** [comment]
Please let it go.

The creator of this addon obviously _wants_ it to be compatible with Enigmail. And they're working on it, in the way that they as experts of the addon deem the most reasonable in terms of time for value. The addon was not created with Enigmail compatibility in mind, and only a really small percentage of Thunderbird users even use Enigmail. So Mozilla (who are trying to get rid of Thunderbird atm anyway) are not going to change anything in the core of their main product (Firefox) just to spare the creator of Send Later any time.

Be happy that they are working on it at all. Integration with Enigmail sounds great to me and I understand that this will require the least rewriting. Please. stop making judgements, like what is and what isn't a good idea. It's not your language that is rude, it is most definitely your attitude.

And I'm writing this in part to show I support the creator's decision. Because I believe support is necessary to encourage someone to work on this jn their free time.

Am 29.05.2016 05:17 schrieb ArsenShnurkov notifications@github.com:

That's not rudeness, it's bad knowledge of English language. I will read something about this.

I see way "a" as most reasonable. And you didn't create feature requests to Thunderbird/Enigmail bugtrackers (because you didn't give links to them, and this is why you don't know the opinion of their maintainers).

I don't believe that cooperation with enigmail addon is a good solution. And I agree that integration into thunderbird is not the proper way to resolve this problem.

I didn't understood the "c" way. If it is possible to rearchitect the addon without changing Thunderbird, then it's your bug, not thunderbird's one. So there should be more details given. Using the word "should" i don't require anything from your and your time, may be it's "it would be nice to do in the ideal world"

**Comment by jikamens** [comment]
New Send Later beta release is compatible with Enigmail: https://addons.mozilla.org/en-US/thunderbird/addon/send-later-3/versions/5.1beta1

Assuming all goes well with the beta, I'll ship release 5.1 to everyone in a week or so.

**Comment by jikamens** [comment]
Version 5.1 has just been released.
