### ISSUE TITLE
Messages should not be deleted from drafts if they fail to send

### ISSUE THREAD

**Issue by mach-o** [jikamens/send-later#2]
When you return to your computer and notice that Thunderbird is asking for your password so that it can send a queued send-later message, entering the password will still usually not succeed because the attempt will have timed out. This is to be expected.

The problem is, after timing out, no copy of the message seems to be retained at all: it disappears from the drafts box and, never having been sent, it doesn't appear in the sent box. This leaves you having to try to retype a message you may initially have composed some time ago.

Why not simply retain a copy in drafts, without being queued to send-later until another the user requests that?

**Comment by jikamens** [comment]
If the message is blocked in sending because you haven't entered your password for your SMTP server, then it should be in your Outbox. If you do File | Send Unsent Messages it should be sent at that point.

If it's not in your Outbox, then that's a Thunderbird bug, not a Send Later bug. By the time Thunderbird prompts for your password to send a scheduled message, Send Later is completely out of the loop -- it has told Thunderbird to processes messages in the Outbox, and no longer has any control.

I don't think leaving a copy in Drafts would be appropriate, because then you'll end up having two copies, one in Outbox and one in Drafts that is redundant cruft.

Frankly, this is not a common use case and not one for which I think a great deal of development effort is justified. If you need to send scheduled messages, then store your password in Thunderbird's password manager so it doesn't need to prompt for it, and all these problems go away.

I understand the desire for increased security, but as noted above, even _with_ the password prompt it should not be the case that messages that trip over this problem are lost completely -- they should remain in your Outbox waiting for you to retry sending them -- so I just don't see sufficient justification for more dev effort here.

If the messages are _not_ being left in your Outbox when this happens, then yeah, that would be a worse deal, so please reopen the ticket if that's the case, and I will investigate further.
