### ISSUE TITLE
Please support Thunderbird 68.3.1

### ISSUE THREAD

**Issue by k-oshiro0322** [jikamens/send-later#28]
My environment display "Send Later is not compatible with Thunderbird 68.3.1"

**Comment by jikamens** [comment]
Send later is compatible with Thunderbird 68.3.1.

If you have it installed from before you upgraded to 68.3.1, then you need to tell Thunderbird to update your add-ons for TB 68, because unfortunately it doesn't do that right away after you switch to TB 68, so add-ons that require an update for TB 68 stop working until either you update manually or it gets around to doing it automatically. To do it manually, open the add-ons page in TB, click on the gear icon, and select the menu item to check for updates. You will have to restart TB after updating.

If you are trying to install Send Later and getting that error, then that is because of a bug in either TB or addons.thunderbird.net which is outside of my control. A few people have reported this issue to me and I don't know what causes it and can't fix it, because Send Later _is_ compatible with TB 68, so if TB claims otherwise, then it's simply wrong, and it's not under my control to fix.

If that's what's happening, then you need to go to [the add-on page](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) _in your browser_, download the add-on and save it on your computer, then go to the add-ons page in TB, click the gear icon, and select the menu item to install an add-on from a file, then select the file you downloaded. This installation method works even when searching and installing within TB doesn't.

**Comment by k-oshiro0322** [comment]
Thank you for your answer.
I have confirmed that the extension is available.
From next update, I want to watch the operation.
